# Generated by Django 4.1.1 on 2022-09-22 06:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faq_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="question",
            field=models.CharField(
                max_length=255,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^.*\\?$", message="Must end with question mark"
                    )
                ],
            ),
        ),
    ]
