stages:
  - build
  - test

default:
  image: ubuntu:20.04
  cache:
    paths:
      - ~/.cache/pip/
  before_script:
    - apt -y update
    - apt -y install apt-utils
    - apt -y install net-tools python3.8 python3-pip
    - apt -y upgrade
    - pip3 install -r requirements/test.txt
    - export DJANGO_SETTINGS_MODULE=devngo_django.settings.test


migrations:
  stage: build
  script:
    - python3 src/manage.py makemigrations
    - python3 src/manage.py migrate
    - python3 src/manage.py check


django-tests:
  stage: test
  script:
    - coverage run src/manage.py test src/
