version: "3"
   
services:
  db:
    image: postgres:13.4-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  web:
    build: .
    image: faq:1.1
    restart: on-failure
    ports:
      - "80:80"
    env_file:
      - .env
    depends_on:
      - db

